name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: hr
          MYSQL_PASSWORD: hr
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: Dziennik_development
        ports: 
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
         
    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby, JRuby and TruffleRuby
      uses: ruby/setup-ruby@v1.33.1
      with:
        ruby-version: head
  
    - name: Build
      run: |
        gem install bundler
        bundle install --jbos 4 --retry 3
        bundle exec rails db:prepare
        bundle exec rails test
        
